In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('australian.csv')
data.columns=['X1','X2','X3','X4','X5','X6','X7','X8','X9','X10','X11','X12','X13','X14','Y']
data

X1     X2      X3  X4  X5  X6     X7  X8  X9  X10  X11  X12  X13  X14  Y
0     0  22.67   7.000   2   8   4  0.165   0   0    0    0    2  160    1  0
1     0  29.58   1.750   1   4   4  1.250   0   0    0    1    2  280    1  0
2     0  21.67  11.500   1   5   3  0.000   1   1   11    1    2    0    1  1
3     1  20.17   8.170   2   6   4  1.960   1   1   14    0    2   60  159  1
4     0  15.83   0.585   2   8   8  1.500   1   1    2    0    2  100    1  1
..   ..    ...     ...  ..  ..  ..    ...  ..  ..  ...  ...  ...  ...  ... ..
684   1  31.57  10.500   2  14   4  6.500   1   0    0    0    2    0    1  1
685   1  20.67   0.415   2   8   4  0.125   0   0    0    0    2    0   45  0
686   0  18.83   9.540   2   6   4  0.085   1   0    0    0    2  100    1  1
687   0  27.42  14.500   2  14   8  3.085   1   1    1    0    2  120   12  1
688   1  41.00   0.040   2  10   4  0.040   0   1    1    0    1  560    1  1

[689 rows x 15 columns]

In [2]:
print('null values in dataset is: \n', data.isnull().sum())
#We can use isnull() method to check whether a cell 
#contains a numeric value ( False ) or if data is missing ( True )
#and used with the sum() method which returns the number of missing values per column

null values in dataset is: 
 X1     0
X2     0
X3     0
X4     0
X5     0
X6     0
X7     0
X8     0
X9     0
X10    0
X11    0
X12    0
X13    0
X14    0
Y      0
dtype: int64


In [3]:
#X = data.drop(['Y'], axis=1).values
#y = data['Y'].values
#X = pd.DataFrame(X)
#X

In [4]:
X = data.iloc[:, :-1].values
Y = data.iloc[:, -1].values

#
# applying One Hot Encoding on columns: 4, 5, 6, 12
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
        transformers = [('one_hot_encoder', OneHotEncoder(categories = 'auto',sparse=False),[4, 5, 6, 12])],
        remainder = 'passthrough')

X = ct.fit_transform(X)

X

array([[ 0.,  0.,  0., ...,  0.,  2.,  1.],
       [ 0.,  0.,  0., ...,  1.,  2.,  1.],
       [ 0.,  0.,  0., ...,  1.,  2.,  1.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  2.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2., 12.],
       [ 0.,  0.,  0., ...,  0.,  1.,  1.]])

In [5]:
# d. min-max normalization to bring all features in similar range

# (value - min) / (max -min)
# copy the data
df_min_max_scaled = X.copy()
  
# apply normalization techniques    
for i in range(0,15):
    df_min_max_scaled[:,i] = (df_min_max_scaled[:,i] - df_min_max_scaled[:,i].min()) / (df_min_max_scaled[:,i].max() - df_min_max_scaled[:,i].min()) 
# view normalized data
print(df_min_max_scaled)

[[ 0.  0.  0. ...  0.  2.  1.]
 [ 0.  0.  0. ...  1.  2.  1.]
 [ 0.  0.  0. ...  1.  2.  1.]
 ...
 [ 0.  0.  0. ...  0.  2.  1.]
 [ 0.  0.  0. ...  0.  2. 12.]
 [ 0.  0.  0. ...  0.  1.  1.]]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2,
                                                    random_state = 0)

#Apply SVM algo on X dataset to get appropriate model

from sklearn import svm
clf = svm.SVC(kernel='linear', C = 0.5, gamma = 'auto') #clf is the model ; C is regularization parameter; Linear kernel used for linearly separable dataset;
# As values of C parameter increases, misclassification will be less . Thus it leads to overfitting as the margin becomes more harder/smaller
# High values of gamma leads to overfitting as it correctly identifies the support vectors and accordingly a harder margin. Its related to Gaussian kernel

clf.fit(X_train, y_train)    #Fit the model

print(clf.intercept_, clf.coef_)  #the theta parameters t0 given by intercept_ , the remaining parameters t1,t2 given by array coef_ . 

theta_0=clf.intercept_
theta = clf.coef_


# Add theta0 with theta array to form a single vector
thetas = np.insert(theta[0],0,theta_0)    #theta_0 added at the front of the array. Index 0

print('thetas ',thetas)